# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
ProductCategory.create!([{ name: 'Mobile'}, { name: 'Clothing'}, { name: 'Shoes'}, { name: 'Books'}, { name: 'Watches'}, { name: 'Accessories'}, { name: 'Home Appliances'}])

Product.create!([{ name: 'Apple iPhone X', description: "The iPhone X was Apple's flagship 10th anniversary iPhone featuring a 5.8-inch OLED display, facial recognition and 3D camera functionality, a glass body, and an A11 Bionic processor.", product_category_id: ProductCategory.find_by(name: "Mobile").id}, { name: 'OnePlus 7 Pro', description: "The OnePlus 7 Pro is a flagship offering from the brand. It comes with a 6.67-inches Quad HD+ Fluid AMOLED display. A Snapdragon 855 SoC powers the device with up to 6GB of RAM and 128GB of internal storage.", product_category_id: ProductCategory.find_by(name: "Mobile").id}, { name: 'Air Max Motion 2 Trainers', description: "Start your day off on the right foot with women's Air Max shoes. Nike Air Max is lightweight, versatile and provides maximum cushioning for all day comfort.", product_category_id: ProductCategory.find_by(name: "Shoes").id}, { name: 'SCARLETTE MINI THREE-HAND DATE BLUSH LEATHER WATCH', description: "Collection: Scarlette Movement Type: Quartz Case Size: 32mm Strap Material: Leather Water Resistant: 5 ATM", product_category_id: ProductCategory.find_by(name: "Watches").id}, { name: 'Samsung Refrigerator', description: "Direct Cool, Single Door: Economical requires manual defrosting Capacity 192 L: Suitable for families with 2-3 members ; Works on Home and Solar Inverter ; Net Dimension (WxHxD)(mm): 532 x 1,192 x 649 Warranty: 1 year on product, 10 years on compressor Energy Rating: 3 Star", product_category_id: ProductCategory.find_by(name: "Home Appliances").id}, { name: 'Black Ball Pen', description: "Black ball pen is widely used to make a note.", product_category_id: ProductCategory.find_by(name: "Books").id , price: "20", discounted_price: "15" }])

ProductVariation.create!([{ variation_name: '64GB', size: "64GB", color: "Black", price: "76900", discounted_price: "51999", product_id: Product.find_by(name: "Apple iPhone X").id }, { variation_name: '64GB', size: "64GB", color: "Red", price: "76900", discounted_price: "51999", product_id: Product.find_by(name: "Apple iPhone X").id }, { variation_name: '128GB', size: "128GB", color: "Blue", price: "81900", discounted_price: "56999", product_id: Product.find_by(name: "Apple iPhone X").id }, { variation_name: '6GB RAM, 128GB Storage', size: "128GB", color: "Mirror Blue", price: "32999", discounted_price: "32999", product_id: Product.find_by(name: "OnePlus 7 Pro").id }, { variation_name: '192 L 3 Star Inverter Direct Cool Single Door Refrigerator (RR20M172ZU2/HL/RR20M272ZU2/NL', size: "192 L", color: "Star flower blue", price: "18250", discounted_price: "13690", product_id: Product.find_by(name: "Samsung Refrigerator").id }])

Purchase.create!([{product_id: Product.find_by(name: "Apple iPhone X").id, product_variation_id: ProductVariation.find_by(variation_name: '6GB RAM, 128GB Storage').id, quantity: 2, total_amount: "103998.0"},{product_id: Product.find_by(name: "Black Ball Pen").id, quantity: 10,total_amount: "150"}])
